import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "~/components/header";
import TransactionForm from "~/components/transaction-form";

const Home: NextPage = () => {
  return (
    <>
        <div
            // className="bg-emerald-600 text-white"
            // className="bg-gradient-to-b from-[#7dd3fc] to-[#15803d]"
        >
      <Head>
        <title>🤑 Millionaire Catalyst 🤑</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header></Header>
        {/* TODO: later all pages should be using this template */}
      <main className="dark:bg-gray-800 flex min-h-screen flex-col items-center justify-center pt-32">
        <TransactionForm/>
      </main>
        </div>
    </>
  );
};

export default Home;
